@startuml

title Get Last Trip Report

autonumber

skinparam roundcorner 10
skinparam shadowing false
skinparam sequence {
  ArrowColor Black
  LifeLineBorderColor #94a4b6
  LifeLineBackgroundColor #d9e8fb
  ParticipantBorderColor #94a4b6
  ParticipantBackgroundColor #d9e8fb
  ParticipantFontSize 13
  MessageAlign center
  NoteBorderColor blue
}
skinparam Note {
  BorderColor black
  BackgroundColor white
}

participant "GMA" as GMA
participant "API Gateway" as API
participant "Trip Report Details Lambda" as Lambda
participant "WISE" as WISE
participant "GCV_LAST_TRIP_REPORT" as DDB
participant "IGNITE" as IGNITE

note over API: SDPR
/ note over Lambda, DDB: FCL

activate GMA
GMA -> API: send request

activate API
API -> Lambda: forward request

activate Lambda
Lambda -> Lambda: dispatch request

Lambda -> WISE: getVehicleDetails
activate WISE
WISE -> Lambda: response
deactivate WISE

alt Vehicle NOT found
  Lambda -> API: return //Vehicle not found//
  API -> GMA: return //Vehicle not found//
end

Lambda -> Lambda: checkServiceId

alt Service NOT enabled
  Lambda -> API: return //Service not enabled//
  API -> GMA: return //Service not enabled//
end

Lambda -> DDB: get enriched //startLocation// and //endLocation//
activate DDB
DDB -> Lambda: response
deactivate DDB

Lambda -> IGNITE: call ""GET /v1/tripreport/tripdetail""
activate IGNITE
IGNITE -> Lambda: response
deactivate IGNITE

Lambda -> WISE: getVehicleCharacteristics
activate WISE
WISE -> Lambda: response
deactivate WISE

alt Vehicle is //BEV// or //PHEV//
  Lambda -> Lambda: keep evMode data
else
  Lambda -> Lambda: hide evMode data
end

Lambda -> API: return last trip report
deactivate Lambda

API -> GMA: return last trip report
deactivate API

deactivate GMA

@enduml